/// Flutter icons FIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FIcon
///      fonts:
///       - asset: fonts/FIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class FIcon {
  FIcon._();

  static const _kFontFam = 'FIcon';
  static const String _kFontPkg = null;

  static const IconData nubank_3__1_ =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mercado_pago_logo__1_ =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData itau_logo__1_ =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData itau__1_ =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uol =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData banco_original =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
